//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CapaPresentacion.WebServiceUtilitario {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSSalaAdminSoap", Namespace="http://tempuri.org/")]
    public partial class WSSalaAdmin : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetInfoPyshicalSlotOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInfoMetersSlotOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetResumenSalaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllUtilitarioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSSalaAdmin() {
            this.Url = global::CapaPresentacion.Properties.Settings.Default.CapaPresentacion_WebServiceUtilitario_WSSalaAdmin;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetInfoPyshicalSlotCompletedEventHandler GetInfoPyshicalSlotCompleted;
        
        /// <remarks/>
        public event GetInfoMetersSlotCompletedEventHandler GetInfoMetersSlotCompleted;
        
        /// <remarks/>
        public event GetResumenSalaCompletedEventHandler GetResumenSalaCompleted;
        
        /// <remarks/>
        public event GetAllUtilitarioCompletedEventHandler GetAllUtilitarioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInfoPyshicalSlot", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InfoSlot GetInfoPyshicalSlot(string codmaquina) {
            object[] results = this.Invoke("GetInfoPyshicalSlot", new object[] {
                        codmaquina});
            return ((InfoSlot)(results[0]));
        }
        
        /// <remarks/>
        public void GetInfoPyshicalSlotAsync(string codmaquina) {
            this.GetInfoPyshicalSlotAsync(codmaquina, null);
        }
        
        /// <remarks/>
        public void GetInfoPyshicalSlotAsync(string codmaquina, object userState) {
            if ((this.GetInfoPyshicalSlotOperationCompleted == null)) {
                this.GetInfoPyshicalSlotOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInfoPyshicalSlotOperationCompleted);
            }
            this.InvokeAsync("GetInfoPyshicalSlot", new object[] {
                        codmaquina}, this.GetInfoPyshicalSlotOperationCompleted, userState);
        }
        
        private void OnGetInfoPyshicalSlotOperationCompleted(object arg) {
            if ((this.GetInfoPyshicalSlotCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInfoPyshicalSlotCompleted(this, new GetInfoPyshicalSlotCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInfoMetersSlot", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InfoSlot GetInfoMetersSlot(string codmaquina) {
            object[] results = this.Invoke("GetInfoMetersSlot", new object[] {
                        codmaquina});
            return ((InfoSlot)(results[0]));
        }
        
        /// <remarks/>
        public void GetInfoMetersSlotAsync(string codmaquina) {
            this.GetInfoMetersSlotAsync(codmaquina, null);
        }
        
        /// <remarks/>
        public void GetInfoMetersSlotAsync(string codmaquina, object userState) {
            if ((this.GetInfoMetersSlotOperationCompleted == null)) {
                this.GetInfoMetersSlotOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInfoMetersSlotOperationCompleted);
            }
            this.InvokeAsync("GetInfoMetersSlot", new object[] {
                        codmaquina}, this.GetInfoMetersSlotOperationCompleted, userState);
        }
        
        private void OnGetInfoMetersSlotOperationCompleted(object arg) {
            if ((this.GetInfoMetersSlotCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInfoMetersSlotCompleted(this, new GetInfoMetersSlotCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetResumenSala", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DineroSlot[] GetResumenSala(System.DateTime fechaIni, System.DateTime fechaFin) {
            object[] results = this.Invoke("GetResumenSala", new object[] {
                        fechaIni,
                        fechaFin});
            return ((DineroSlot[])(results[0]));
        }
        
        /// <remarks/>
        public void GetResumenSalaAsync(System.DateTime fechaIni, System.DateTime fechaFin) {
            this.GetResumenSalaAsync(fechaIni, fechaFin, null);
        }
        
        /// <remarks/>
        public void GetResumenSalaAsync(System.DateTime fechaIni, System.DateTime fechaFin, object userState) {
            if ((this.GetResumenSalaOperationCompleted == null)) {
                this.GetResumenSalaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetResumenSalaOperationCompleted);
            }
            this.InvokeAsync("GetResumenSala", new object[] {
                        fechaIni,
                        fechaFin}, this.GetResumenSalaOperationCompleted, userState);
        }
        
        private void OnGetResumenSalaOperationCompleted(object arg) {
            if ((this.GetResumenSalaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetResumenSalaCompleted(this, new GetResumenSalaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllUtilitario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetAllUtilitario(System.DateTime fechaIni, System.DateTime fechaFin) {
            object[] results = this.Invoke("GetAllUtilitario", new object[] {
                        fechaIni,
                        fechaFin});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllUtilitarioAsync(System.DateTime fechaIni, System.DateTime fechaFin) {
            this.GetAllUtilitarioAsync(fechaIni, fechaFin, null);
        }
        
        /// <remarks/>
        public void GetAllUtilitarioAsync(System.DateTime fechaIni, System.DateTime fechaFin, object userState) {
            if ((this.GetAllUtilitarioOperationCompleted == null)) {
                this.GetAllUtilitarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllUtilitarioOperationCompleted);
            }
            this.InvokeAsync("GetAllUtilitario", new object[] {
                        fechaIni,
                        fechaFin}, this.GetAllUtilitarioOperationCompleted, userState);
        }
        
        private void OnGetAllUtilitarioOperationCompleted(object arg) {
            if ((this.GetAllUtilitarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllUtilitarioCompleted(this, new GetAllUtilitarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InfoSlot {
        
        private string[] listaTicketInField;
        
        private string[] listaTicketOutField;
        
        private decimal coininField;
        
        private decimal coinOutField;
        
        private decimal jackpotField;
        
        private decimal cancelCreditsField;
        
        private decimal handPayField;
        
        private decimal gamesPlayedField;
        
        private decimal trueInField;
        
        private decimal trueOutField;
        
        private decimal totalDropField;
        
        private decimal billField;
        
        private decimal bill1Field;
        
        private decimal bill2Field;
        
        private decimal bill5Field;
        
        private decimal bILL10Field;
        
        private decimal bILL20Field;
        
        private decimal bILL50Field;
        
        private decimal bill100Field;
        
        private decimal ticketInField;
        
        private decimal ticketOutField;
        
        private decimal eftInField;
        
        private decimal eftOutField;
        
        private decimal ticketBonusInField;
        
        private decimal ticketBonusOutField;
        
        private decimal tapebwField;
        
        private decimal tappwField;
        
        private decimal tmpebwField;
        
        private decimal tmppwField;
        
        /// <remarks/>
        public string[] listaTicketIn {
            get {
                return this.listaTicketInField;
            }
            set {
                this.listaTicketInField = value;
            }
        }
        
        /// <remarks/>
        public string[] listaTicketOut {
            get {
                return this.listaTicketOutField;
            }
            set {
                this.listaTicketOutField = value;
            }
        }
        
        /// <remarks/>
        public decimal Coinin {
            get {
                return this.coininField;
            }
            set {
                this.coininField = value;
            }
        }
        
        /// <remarks/>
        public decimal CoinOut {
            get {
                return this.coinOutField;
            }
            set {
                this.coinOutField = value;
            }
        }
        
        /// <remarks/>
        public decimal Jackpot {
            get {
                return this.jackpotField;
            }
            set {
                this.jackpotField = value;
            }
        }
        
        /// <remarks/>
        public decimal CancelCredits {
            get {
                return this.cancelCreditsField;
            }
            set {
                this.cancelCreditsField = value;
            }
        }
        
        /// <remarks/>
        public decimal HandPay {
            get {
                return this.handPayField;
            }
            set {
                this.handPayField = value;
            }
        }
        
        /// <remarks/>
        public decimal GamesPlayed {
            get {
                return this.gamesPlayedField;
            }
            set {
                this.gamesPlayedField = value;
            }
        }
        
        /// <remarks/>
        public decimal TrueIn {
            get {
                return this.trueInField;
            }
            set {
                this.trueInField = value;
            }
        }
        
        /// <remarks/>
        public decimal TrueOut {
            get {
                return this.trueOutField;
            }
            set {
                this.trueOutField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalDrop {
            get {
                return this.totalDropField;
            }
            set {
                this.totalDropField = value;
            }
        }
        
        /// <remarks/>
        public decimal Bill {
            get {
                return this.billField;
            }
            set {
                this.billField = value;
            }
        }
        
        /// <remarks/>
        public decimal Bill1 {
            get {
                return this.bill1Field;
            }
            set {
                this.bill1Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Bill2 {
            get {
                return this.bill2Field;
            }
            set {
                this.bill2Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Bill5 {
            get {
                return this.bill5Field;
            }
            set {
                this.bill5Field = value;
            }
        }
        
        /// <remarks/>
        public decimal BILL10 {
            get {
                return this.bILL10Field;
            }
            set {
                this.bILL10Field = value;
            }
        }
        
        /// <remarks/>
        public decimal BILL20 {
            get {
                return this.bILL20Field;
            }
            set {
                this.bILL20Field = value;
            }
        }
        
        /// <remarks/>
        public decimal BILL50 {
            get {
                return this.bILL50Field;
            }
            set {
                this.bILL50Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Bill100 {
            get {
                return this.bill100Field;
            }
            set {
                this.bill100Field = value;
            }
        }
        
        /// <remarks/>
        public decimal TicketIn {
            get {
                return this.ticketInField;
            }
            set {
                this.ticketInField = value;
            }
        }
        
        /// <remarks/>
        public decimal TicketOut {
            get {
                return this.ticketOutField;
            }
            set {
                this.ticketOutField = value;
            }
        }
        
        /// <remarks/>
        public decimal EftIn {
            get {
                return this.eftInField;
            }
            set {
                this.eftInField = value;
            }
        }
        
        /// <remarks/>
        public decimal EftOut {
            get {
                return this.eftOutField;
            }
            set {
                this.eftOutField = value;
            }
        }
        
        /// <remarks/>
        public decimal TicketBonusIn {
            get {
                return this.ticketBonusInField;
            }
            set {
                this.ticketBonusInField = value;
            }
        }
        
        /// <remarks/>
        public decimal TicketBonusOut {
            get {
                return this.ticketBonusOutField;
            }
            set {
                this.ticketBonusOutField = value;
            }
        }
        
        /// <remarks/>
        public decimal tapebw {
            get {
                return this.tapebwField;
            }
            set {
                this.tapebwField = value;
            }
        }
        
        /// <remarks/>
        public decimal tappw {
            get {
                return this.tappwField;
            }
            set {
                this.tappwField = value;
            }
        }
        
        /// <remarks/>
        public decimal tmpebw {
            get {
                return this.tmpebwField;
            }
            set {
                this.tmpebwField = value;
            }
        }
        
        /// <remarks/>
        public decimal tmppw {
            get {
                return this.tmppwField;
            }
            set {
                this.tmppwField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DineroSlot {
        
        private decimal tot_ventField;
        
        private decimal tot_pmField;
        
        private decimal tot_mfField;
        
        private decimal tot_x_billeteroField;
        
        private decimal monto_mastercardField;
        
        private decimal monto_visaField;
        
        private decimal monto_otrosField;
        
        private decimal montoVentaTicketsField;
        
        private decimal montoCompraTicketsField;
        
        private decimal ventaTragamonedasField;
        
        private System.DateTime fechaField;
        
        /// <remarks/>
        public decimal tot_vent {
            get {
                return this.tot_ventField;
            }
            set {
                this.tot_ventField = value;
            }
        }
        
        /// <remarks/>
        public decimal tot_pm {
            get {
                return this.tot_pmField;
            }
            set {
                this.tot_pmField = value;
            }
        }
        
        /// <remarks/>
        public decimal tot_mf {
            get {
                return this.tot_mfField;
            }
            set {
                this.tot_mfField = value;
            }
        }
        
        /// <remarks/>
        public decimal tot_x_billetero {
            get {
                return this.tot_x_billeteroField;
            }
            set {
                this.tot_x_billeteroField = value;
            }
        }
        
        /// <remarks/>
        public decimal monto_mastercard {
            get {
                return this.monto_mastercardField;
            }
            set {
                this.monto_mastercardField = value;
            }
        }
        
        /// <remarks/>
        public decimal monto_visa {
            get {
                return this.monto_visaField;
            }
            set {
                this.monto_visaField = value;
            }
        }
        
        /// <remarks/>
        public decimal monto_otros {
            get {
                return this.monto_otrosField;
            }
            set {
                this.monto_otrosField = value;
            }
        }
        
        /// <remarks/>
        public decimal montoVentaTickets {
            get {
                return this.montoVentaTicketsField;
            }
            set {
                this.montoVentaTicketsField = value;
            }
        }
        
        /// <remarks/>
        public decimal montoCompraTickets {
            get {
                return this.montoCompraTicketsField;
            }
            set {
                this.montoCompraTicketsField = value;
            }
        }
        
        /// <remarks/>
        public decimal VentaTragamonedas {
            get {
                return this.ventaTragamonedasField;
            }
            set {
                this.ventaTragamonedasField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetInfoPyshicalSlotCompletedEventHandler(object sender, GetInfoPyshicalSlotCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInfoPyshicalSlotCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInfoPyshicalSlotCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InfoSlot Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InfoSlot)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetInfoMetersSlotCompletedEventHandler(object sender, GetInfoMetersSlotCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInfoMetersSlotCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInfoMetersSlotCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InfoSlot Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InfoSlot)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetResumenSalaCompletedEventHandler(object sender, GetResumenSalaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetResumenSalaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetResumenSalaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DineroSlot[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DineroSlot[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetAllUtilitarioCompletedEventHandler(object sender, GetAllUtilitarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllUtilitarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllUtilitarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591